apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "populators.populator.k8s.io"
spec:
  group: "populator.k8s.io"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "populators"
    singular: "populator"
    kind: "Populator"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["type"]
          properties:
            type:
              type: "string"
