apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-restore
  annotations:
      foo: bar
spec:
  dataSource:
    name: demo-populator
    kind: VolumePopulator
    apiGroup: populator.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
